app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import login
from datetime import datetime

class User(UserMixin):
    def __init__(self, email, password):
        self.email = email 
        self.password = password

@login.user_loader
def load_user():
    return User()

app/__init__.py
from flask import Flask
from config import Config
from flask_bootstrap import Bootstrap

from flask_login import LoginManager

bootstrap = Bootstrap()
login = LoginManager()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initializing Flask Extensions
    bootstrap.init_app(app)
    login.init_app(app)
    

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes, forms

app/main/routes.py
from flask import render_template, redirect, url_for
from flask_login import current_user
from app.main import bp

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/backend')
def backend():
    return render_template('backend.html')


app/templates/backend.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{{url_for('auth.login')}}">Login</a>
    <a href="{{ url_for('auth.signup') }}">Sign up</a>
    <a href="{{url_for('auth.logout')}}">Logout</a>
</body>
</html>

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Typing App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}" media="all">
</head>
<body>
    <!-- navigation(add here for all pages)-->
    {% block navbar %} {% include 'navbar.html' %} {% endblock %}
    {% block content %}{% endblock %} 
</body>
</html>

app/templates/index.html
<<<<<<< HEAD
{% extends 'base.html' %}

{%block content%}
    <div class="container">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <div class="intro">
                <h2 style="font-size: 40px; padding-top: 40px;">The Best way to Enhance<br> Your Typing Speed</h2>
        
                <br><br>

                <p class= "text-muted" style="font-size: 18px;">typing app offers a fun way to get better at the thing you do <br>
                everyday:typing</p>           
                <br>
                <p class= "text-muted" style="font-size: 18px;" >Don't practice until you get it right,
                <br>Practice until you can't get it wrong.</p>
                <br><br>
                <a href="{{ url_for('main.backend') }}"><button class="btn btn-secondary">Create a Free Account</button> </a>
            </div>
            <div class=" fav-texts text-center " style= "background-color:rgba(245, 240, 240, 0.911)">
                <h3 style="font-size: 30px;" >Use Your Favorite Texts!</h3>
                <br><br>
                <p class="text-muted" style="font-size:18px;"  >Are you an avid reader, a singer, or a poet? You can useany text you<br>
                    want to with typing app.<br><br>
                    This brings all the fun you have with your other activities to typing. So<br>
                    no more boredom and no more not practising because typing isn't<br>
                    engaging
                <p><br><br><br>
            </div>
            <div class="text-center">
                <h3 style="font-size: 30px;">Become the Best</h3>
                <br><br>
                <p class="text-muted" style="font-size:18px;">Are you competitive or someone who wants to track their progress?<br>
                    Typing board provides a leaderboard that allows<br>
                    you to know your position in the pack.
                <p><br><br><br>
            </div>

        </div>
        <div class="col-md-1"></div>
    </div>

{% endblock %}
=======
{% extends 'base.html' %}

{%block content%}

    <div class="container">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <div class="intro">
                <h2 style="font-size: 40px; padding-top: 40px;">The Best way to Enhance<br> Your Typing Speed</h2>
        
                <br><br>

<a href="{{ url_for('main.backend') }}"
<div class="home">
  <div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div>
        <h2 id="title" style="font-size: 50px; font-family: 'Lobster', cursive;  padding-top: 40px; text-align: center;">
          Welcome to Typing-App</h2>
        <hr>


                <p class= "text-muted" style="font-size: 18px;">typing app offers a fun way to get better at the thing you do <br>
                everyday:typing</p>           
                <br>
                <p class= "text-muted">Don't practice until you get it right,
                <br>Practice until you can't get it wrong.</p>
                <br><br>
                <a href="#"><button class="btn btn-secondary">Create a Free Account</button> </a>
            </div>
            <div class=" fav-texts jumbotron text-center " style= "background-color:rgba(255, 255, 255, 0.836)">
                <h3>Use Your Favorite Texts!</h3>
                <br><br>
                <p class="text-muted">Are you an avid reader, a singer, or a poet? You can useany text you<br>
                    want to with typing app.<br><br>
                    This brings all the fun you have with your other activities to typing. So<br>
                    no more boredom and no more not practising because typing isn't<br>
                    engaging
                <p><br><br><br>
            </div>
            <div class="text-center">
                <h3 style="font-size: 40px; font-weight: bold;">Become the Best</h3>
                <br><br>
                <p class="text-muted" style="font-size:18px; line-height: 3px;">Are you competitive or someone who wants to track their progress?<br>
                    Typing board provides a leaderboard that allows<br>
                    you to know your position in the pack.
                <p><br><br><br>
            </div>

        </div>
        <div class="col-md-1"></div>
    </div>

{% endblock %}
>>>>>>> 47bbae6bf2c6dfa4b3550c1625825a661e9b349e

app/templates/navbar.html
<div class="container"  style="margin-left:400px;">
    <nav class="navbar ">
        <div class=" container-fluid " style="text-decoration: none; color: #fff;">
            <div class="navbar-header ">
                <button type="button " class="navbar-toggle " data-toggle="collapse " data-target=".navbar-collapse ">
                    <span class="sr-only ">Toggle navigation</span>
                    <span class="icon-bar "></span>
                    <span class="icon-bar "></span>
                    <span class="icon-bar "></span>
                </button>
                <a href="/ " class="navbar-brand "><Strong>TYPING APP</Strong></a>
            </div>
            <div class="navbar-collapse collapse ">
                <ul class="nav navbar-nav ">
                    <li>
                        <a href="/ " style="text-decoration: none;">HOME</a>
                    </li>
    
                <ul class="nav navbar-nav navbar-right ">
                    {% if current_user.is_authenticated %}

                    <li>
                        <a href="{{url_for( 'auth.signup')}} " style="text-decoration: none; ">SIGN UP</a>
                    </li>

                    </li>
                    {% else %}

                    <li>
                        <a href="{{url_for( 'auth.login')}} " style="text-decoration: none; ">LOGIN</a>
                    </li>
                    
                    <li>
                        <a href="{{url_for( 'auth.logout')}} " style="text-decoration: none; ">LOGOUT</a>
                    </li>

                </ul>
                {%endif%}
            </div>
        </div>
        </div>
    </nav>
</div>